import { AppShell } from "@/components/layout/AppShell";
import { CameraPanel } from "@/components/pool/CameraPanel";
import { PoolMetrics } from "@/components/pool/PoolMetrics";
import { RobotControls } from "@/components/pool/RobotControls";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Shield, Wifi } from "lucide-react";

export default function Dashboard() {
  return (
    <AppShell>
      <div className="space-y-6">
        <div className="flex flex-col gap-3 md:flex-row md:items-end md:justify-between">
          <div>
            <h1 className="text-2xl font-bold tracking-tight">Pool Control Board</h1>
            <p className="text-muted-foreground">Live feed, water quality, alerts, and robot control</p>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant="secondary" className="uppercase">Online</Badge>
            <Wifi className="h-4 w-4 text-emerald-500" />
          </div>
        </div>
        <PoolMetrics />
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-5">
          <div className="lg:col-span-3">
            <CameraPanel />
          </div>
          <div className="lg:col-span-2">
            <RobotControls />
            <Card className="mt-6">
              <CardHeader>
                <CardTitle className="flex items-center gap-2"><Shield className="h-5 w-5 text-primary" /> Safety Notices</CardTitle>
              </CardHeader>
              <CardContent className="text-sm text-muted-foreground">
                <p>Alerts are generated by the onboard vision model and water sensors. Manual control is disabled while in Auto mode.</p>
                <Separator className="my-3" />
                <p>Integrate your camera RTSP/HTTP streams and robot API endpoints to go live.</p>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </AppShell>
  );
}
